# Goals

* Merge all datasets into one

In [ ]:
from datasets import load_dataset
import pandas as pd

omset_l = load_dataset("Om1024/racist-sexist")
davidset_l = load_dataset("tdavidson/hate_speech_offensive")

omset = omset_l["train"].to_pandas()
davidset = davidset_l["train"].to_pandas()
# new train_hate path: /home/sam/Projects/Senior Capstone/CapstoneProject/Data/train_hate_mod.csv
train_hate = pd.read_csv("/home/sam/Projects/Senior Capstone/CapstoneProject/Data/train_labeled_hate_seniment.csv")
# new jig_train path: /home/sam/Projects/Senior Capstone/CapstoneProject/Data/jigsaw_data/jig_train_mod.csv
jig_train = pd.read_csv("/home/sam/Projects/Senior Capstone/CapstoneProject/Data/jigsaw_data/train_multiLabled_jigswaw.csv")
jig_test = pd.read_csv("/home/sam/Projects/Senior Capstone/CapstoneProject/Data/jigsaw_data/test.csv")
jig_test_labels = pd.read_csv("/home/sam/Projects/Senior Capstone/CapstoneProject/Data/jigsaw_data/test_labels.csv")

/var/data/python/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/tmp/ipykernel_297/1741326937.py:9: DtypeWarning: Columns (2,3,6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40) have mixed types. Specify dtype option on import or set low_memory=False.
  train_hate = pd.read_csv("/home/sam/Projects/Senior Capstone/CapstoneProject/Data/train_labeled_hate_seniment.csv")
/tmp/ipykernel_297/1741326937.py:10: DtypeWarning: Columns (7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  jig_train = pd.read_csv("/home/sam/Projects/Senior Capstone/CapstoneProject/Data/jigsaw_data/train_multiLabled_jigswaw.csv")

In [3]:
# hate speech = 0, offensive language = 1, neither = 2
davidset.to_csv('/home/sam/Projects/Senior Capstone/CapstoneProject/Data/david_hate_speech.csv')

In [ ]:
vicom_labels = pd.read_csv("/home/sam/Projects/Senior Capstone/CapstoneProject/Data/vicom_data/annotations_metadata.csv")

In [10]:
print(vicom_labels.shape)

(10944, 5)

In [12]:
# Check if all file_ids match filenames in your directory
vicom_files = "/home/sam/Projects/Senior Capstone/CapstoneProject/Data/vicom_data/all_files"
filenames = [os.path.splitext(file)[0] for file in os.listdir(vicom_files)]
missing_files = vicom_labels[~vicom_labels['file_id'].isin(filenames)]
print(f"Number of rows with no matching file: {len(missing_files)}")

# Check if there are labels other than 'noHate' or 'hate'
other_labels = vicom_labels[~vicom_labels['label'].isin(['noHate', 'hate'])]
print(f"Number of rows with other labels: {len(other_labels)}")
print(vicom_labels['label'].unique())  # See all unique label values

Number of rows with no matching file: 0
Number of rows with other labels: 241
['noHate' 'hate' 'idk/skip' 'relation']

In [ ]:
# Drop rows where label is 'idk/skip' or 'relation'
vicom_labels = vicom_labels[~vicom_labels['label'].isin(['idk/skip', 'relation'])]

# Verify the labels are now only 'noHate' and 'hate'
print(vicom_labels['label'].unique())

['noHate' 'hate']

/tmp/ipykernel_268/1135549136.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vicom_labels['num_labels'] = vicom_labels['num_labels'].astype('int64')

In [14]:
import numpy as np
import os

vicom_labels['num_labels'] = np.nan

vicom_files = "/home/sam/Projects/Senior Capstone/CapstoneProject/Data/vicom_data/all_files"

for file in os.listdir(vicom_files):
    filename = os.fsdecode(file)

    filename, ext = os.path.splitext(filename)

    # find rows where file_id == filename
    mask = (vicom_labels['file_id'] == filename)

    if mask.any():
        label = vicom_labels.loc[mask, 'label'].iloc[0]

        if label == 'noHate':
            vicom_labels.loc[mask, 'num_labels'] = 0
        elif label == 'hate':
            vicom_labels.loc[mask, 'num_labels'] = 1

/tmp/ipykernel_268/2935678807.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vicom_labels['num_labels'] = np.nan

In [17]:
vicom_labels['num_labels'] = vicom_labels['num_labels'].astype('int64')

/tmp/ipykernel_268/1124249076.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vicom_labels['num_labels'] = vicom_labels['num_labels'].astype('int64')

In [18]:
vicom_labels

          file_id  user_id  subforum_id  num_contexts   label  num_labels
0      12834217_1   572066         1346             0  noHate           0
1      12834217_2   572066         1346             0  noHate           0
2      12834217_3   572066         1346             0  noHate           0
3      12834217_4   572066         1346             0    hate           1
4      12834217_5   572066         1346             0  noHate           0
...           ...      ...          ...           ...     ...         ...
10939  33676864_5   734541         1388             0  noHate           0
10940  33677019_1   735154         1388             0  noHate           0
10941  33677019_2   735154         1388             0  noHate           0
10942  33677053_1   572266         1388             0    hate           1
10943  33677053_2   572266         1388             0  noHate           0

[10703 rows x 6 columns]

In [4]:
type(vicom_labels['num_labels'][2])

numpy.float64

In [ ]:
jig_test_mrgd = pd.merge(jig_test, jig_test_labels, how='outer')

In [ ]:
omset

,Unnamed: 0,text,sexist,racist,neutral
0,0,How dare you give me free food I don't like - ...,0,0,1
1,1,Melania Trump: ‏ I had a wonderful visit to WR...,0,0,1
2,2,Migrant kids sexually assault a little girl an...,0,0,1
3,3,Women hate vulnerable men,1,0,0
4,4,I'm not the one celebrating a fucking high-gra...,1,0,0
...,...,...,...,...,...
11875,11875,There is a very valid case to be made that str...,0,0,1
11876,11876,/cast Spectral Guys\n\nParty time,0,0,1
11877,11877,I try to make the left as retarded as possible...,0,0,1
11878,11878,Perhaps its just re-living its youth & pretend...,1,0,0
11879,11879,I love black people I think we should all own ...,0,1,0

In [2]:
import numpy as np
omset['comb_labels'] = np.nan

# funciton to combine omeset labels

def omcomb(sex, rac, nuet):

    # inverting label for neutral rows

    if nuet == 1:
        omset[nuet, 'comb_labels'] = 0

    if sex or rac == 1:
        omset[sex, 'comb_labels'] = 1
    
    return

##### Bad Code Don't Run ^^

In [10]:
def omcomb(row):
    
    if row['neutral'] == 1:
        return 0
    
    elif row['sexist'] == 1 or row['racist'] == 1:
        return 1
    
    else:
        return np.nan

In [11]:
omset['comb_labels'] = omset.apply(omcomb, axis=1)

In [12]:
omset

,Unnamed: 0,text,sexist,racist,neutral,comb_labels
0,0,How dare you give me free food I don't like - ...,0,0,1,0
1,1,Melania Trump: ‏ I had a wonderful visit to WR...,0,0,1,0
2,2,Migrant kids sexually assault a little girl an...,0,0,1,0
3,3,Women hate vulnerable men,1,0,0,1
4,4,I'm not the one celebrating a fucking high-gra...,1,0,0,1
...,...,...,...,...,...,...
11875,11875,There is a very valid case to be made that str...,0,0,1,0
11876,11876,/cast Spectral Guys\n\nParty time,0,0,1,0
11877,11877,I try to make the left as retarded as possible...,0,0,1,0
11878,11878,Perhaps its just re-living its youth & pretend...,1,0,0,1
11879,11879,I love black people I think we should all own ...,0,1,0,1

In [ ]:
print("jig_train shape: ", jig_train.shape)

# 0.3% is indentity hate
print("identity hate counts: ", jig_train['identity_hate'].value_counts()[1])

# 9% is toxic
print("toxic counts: ", jig_train['toxic'].value_counts()[1])

# % is severe_toxic 
print("severe_toxic counts: ", jig_train['severe_toxic'].value_counts()[1])

# % is obscene
print("obscene counts: ", jig_train['obscene'].value_counts()[1])

# % is threat
print("threat counts: ", jig_train['threat'].value_counts()[1])

# % is insult
print("insult counts: ", jig_train['insult'].value_counts()[1])

print("train_hate shape: ", train_hate.shape)

# 44% are hate
print("train_hate counts: ", train_hate['label'].value_counts()[1])

print(omset.shape)

# % are racist
print("racist counts: ", omset['racist'].value_counts()[1])

# % are sexist
print("sexist counts: ", omset['sexist'].value_counts()[1])

print(davidset.shape)

jig_train shape:  (159571, 20)
identity hate counts:  555
toxic counts:  15260
severe_toxic counts:  1620
obscene counts:  8438
threat counts:  493
insult counts:  7864
train_hate shape:  (50740, 41)
train_hate counts:  2242

/tmp/ipykernel_279/82534768.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("toxic counts: ", jig_train['toxic'].value_counts()[1])
/tmp/ipykernel_279/82534768.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("severe_toxic counts: ", jig_train['severe_toxic'].value_counts()[1])
/tmp/ipykernel_279/82534768.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("obscene counts: ", jig_train['obscene'].value_counts()[1])
/tmp/ipykernel_279/82534768.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("threat counts: ", jig_train['threat'].value_counts()[1])
/tmp/ipykernel_279/82534768.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("insult counts: ", jig_train['insult'].value_counts()[1])

In [3]:
train_hate

,id,label,tweet,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
0,1.0,0.0,@user when a father is dysfunctional and is s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,0.0,@user @user thanks for #lyft credit i can't us...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,0.0,bihday your majesty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,0.0,#model i love u take with u all the time in ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,0.0,factsguide: society now #motivation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
train_hate = train_hate[~train_hate['label'].isna()]

In [21]:
# Count NaN values in the 'label' column
nan_count = train_hate['label'].isna().sum()
print(f"Number of NaN values: {nan_count}")

Number of NaN values: 0

In [22]:
train_hate

,id,label,tweet,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
0,1.0,0.0,@user when a father is dysfunctional and is s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,0.0,@user @user thanks for #lyft credit i can't us...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,0.0,bihday your majesty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,0.0,#model i love u take with u all the time in ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,0.0,factsguide: society now #motivation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31957,31958.0,0.0,ate @user isz that youuu?ðððððð...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31958,31959.0,0.0,to see nina turner on the airwaves trying to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31959,31960.0,0.0,listening to sad songs on a monday morning otw...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31960,31961.0,1.0,"@user #sikh #temple vandalised in in #calgary,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31961,31962.0,0.0,thank you @user for you follow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# type casting
train_hate['label'] = train_hate['label'].astype('int64')

/tmp/ipykernel_297/1558788411.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_hate['label'] = train_hate['label'].astype('int64')

In [6]:
train_hate.to_csv('/home/sam/Projects/Senior Capstone/CapstoneProject/Data/train_hate_mod.csv')

### Maybe get rid of the extraa columns in train_hate

In [24]:
train_hate

,id,label,tweet,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40
0,1.0,0,@user when a father is dysfunctional and is s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,0,@user @user thanks for #lyft credit i can't us...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,0,bihday your majesty,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,0,#model i love u take with u all the time in ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,0,factsguide: society now #motivation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31957,31958.0,0,ate @user isz that youuu?ðððððð...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31958,31959.0,0,to see nina turner on the airwaves trying to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31959,31960.0,0,listening to sad songs on a monday morning otw...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31960,31961.0,1,"@user #sikh #temple vandalised in in #calgary,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31961,31962.0,0,thank you @user for you follow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
jig_train

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
jig_cols = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

for col in jig_cols:
    jig_train[col] = pd.to_numeric(jig_train[col], downcast='integer', errors='coerce')
    nan_count = jig_train[col].isna().sum()
    if nan_count > 0:
        print(f"Found {nan_count} NaN values in {col} after conversion")

    print(f"{col} data type after conversion: {jig_train[col].dtype}")

toxic data type after conversion: int8
severe_toxic data type after conversion: int8
obscene data type after conversion: int8
threat data type after conversion: int8
insult data type after conversion: int8
identity_hate data type after conversion: int8

In [17]:
for col in jig_cols:

    jig_train = jig_train[~jig_train[col].isna()]
    print(f"{col} data type after conversion: {jig_train[col].dtype}")

toxic data type after conversion: float64
severe_toxic data type after conversion: float64
obscene data type after conversion: float64
threat data type after conversion: float64
insult data type after conversion: float64
identity_hate data type after conversion: float64

In [16]:
def jigcomb(row):

    if row['toxic'] == 1 or row['severe_toxic'] == 1 or row['obscene'] == 1 or row['threat'] == 1 or row['insult'] == 1 or row['identity_hate'] == 1:
        return 1
    
    else:
        return 0

In [19]:
import numpy as np

jig_train['join_label'] = np.nan

jig_train['join_label'] = jig_train.apply(jigcomb, axis=1)

In [28]:
jig_train

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,join_label
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159566,ffe987279560d7ff,""":::::And for the second time of asking, when ...",0,0,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
159567,ffea4adeee384e90,You should be ashamed of yourself \n\nThat is ...,0,0,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
159568,ffee36eab5c267c9,"Spitzer \n\nUmm, theres no actual article for ...",0,0,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
159569,fff125370e4aaaf3,And it looks like it was actually you who put ...,0,0,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
159570,fff46fc426af1f9a,"""\nAnd ... I really don't think you understand...",0,0,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [20]:
print(jig_train['join_label'].value_counts()[1])

16191

In [21]:
jig_train.to_csv('/home/sam/Projects/Senior Capstone/CapstoneProject/Data/jigsaw_data/jig_train_mod.csv')