# Goals
* lemmatize tokens
* encoding
* normalization
* noise removal
* add padding to text to standardize length
* lowercasing text
* attention masking

In [ ]:
import nltk
import pandas as pd
import ast

df_drct_frm_csv = pd.read_csv('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/tokenized_df.csv')

df = pd.DataFrame()

def safe_literal_eval(val):
    if pd.isna(val):  # Check if the value is NaN
        return []  # Return empty list for NaN values
    try:
        return ast.literal_eval(val)
    except (ValueError, SyntaxError):
        # If it can't be evaluated as a list, return empty list
        return []

df = df_drct_frm_csv

# Apply the safe function
df['tokenized_text_words'] = df_drct_frm_csv['tokenized_text_words'].apply(safe_literal_eval)
df['tokenized_text_sents'] = df_drct_frm_csv['tokenized_text_sents'].apply(safe_literal_eval)

# stemming and lemmatization

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords
import numpy as np

df['porter_stem_words'] = [[] for _ in range(len(df))]
df['snow_stem_words'] = [[] for _ in range(len(df))]
df['porter_stem_sents'] = [[] for _ in range(len(df))]
df['snow_stem_sents'] = [[] for _ in range(len(df))]
df['lemma_words'] = [[] for _ in range(len(df))]
df['lemma_sents'] = [[] for _ in range(len(df))]

stop_words = set(stopwords.words('english'))
stemmer_ps = PorterStemmer()
stemmer_ss = SnowballStemmer('english')

## Stemming

### Porter

# First dividing by word then rejoining into a sentences

In [ ]:
# words
for index, row in df.iterrows():
  stemmed_words = []

  for word in row['tokenized_text_words']:
     if word not in stop_words:
      try:
        stemmed_word = stemmer_ps.stem(word)
        stemmed_words.append(stemmed_word)
      except RecursionError:
        print(f'RecursionError in row {index} on word: {word}')
        continue
  df.at[index, 'porter_stem_words'] = stemmed_words

RecursionError in row 179584 on word: yyyyyyyyyyyyyyybvgtfrrrrrbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

In [ ]:
# stemming

for index, row in df.iterrows():
    stemmed_sents = []

    for sent in row['tokenized_text_sents']:
        # Split sentence into words
        words = sent.split()

        # Stem each word individually
        stemmed_words_in_sent = []
        for word in words:
            try:
                stemmed_word = stemmer_ps.stem(word)
                stemmed_words_in_sent.append(stemmed_word)
            except RecursionError:
                print(f'RecursionError in row {index} on word: {word}')
                # Use original word if stemming fails
                stemmed_words_in_sent.append(word)

        # Rejoin the stemmed words into a sentence
        stemmed_sent = ' '.join(stemmed_words_in_sent)
        stemmed_sents.append(stemmed_sent)

    # Assign the stemmed sentences to the current row
    df.at[index, 'porter_stem_sents'] = stemmed_sents

RecursionError in row 179584 on word: yyyyyyyyyyyyyyybvgtfrrrrrbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

### Snowball

In [ ]:
# words
for index, row in df.iterrows():
  stemmed_words = []

  for word in row['tokenized_text_words']:
     if word not in stop_words:
      try:
        stemmed_word = stemmer_ss.stem(word)
        stemmed_words.append(stemmed_word)
      except RecursionError:
        print(f'RecursionError in row {index} on word: {word}')
        continue
  df.at[index, 'snow_stem_words'] = stemmed_words

In [ ]:
for index, row in df.iterrows():
    stemmed_sents = []

    for sent in row['tokenized_text_sents']:
        # Split sentence into words
        words = sent.split()

        # Stem each word individually
        stemmed_words_in_sent = []
        for word in words:
            try:
                stemmed_word = stemmer_ss.stem(word)
                stemmed_words_in_sent.append(stemmed_word)
            except RecursionError:
                print(f'RecursionError in row {index} on word: {word}')
                # Use original word if stemming fails
                stemmed_words_in_sent.append(word)

        # Rejoin the stemmed words into a sentence
        stemmed_sent = ' '.join(stemmed_words_in_sent)
        stemmed_sents.append(stemmed_sent)

    # Assign the stemmed sentences to the current row
    df.at[index, 'snow_stem_sents'] = stemmed_sents

NameError: name 'stemmer_ss' is not defined

In [ ]:
df.head()

,Unnamed: 0,text,tokenized_text_words,tokenized_text_sents,label,porter_stem_words,snow_stem_words,porter_stem_sents,snow_stem_sents,lemma_words,lemma_sents
0,0,Thank you for understanding. I think very high...,"[Thank, you, for, understanding, ., I, think, ...","[Thank you for understanding., I think very hi...",0,"[thank, understand, ., i, think, highli, would...","[thank, understand, ., i, think, high, would, ...","[thank you for understanding., i think veri hi...","[thank you for understanding., i think veri hi...",[],[]
1,1,:Dear god this site is horrible.,"[:, Dear, god, this, site, is, horrible, .]",[:Dear god this site is horrible.],0,"[:, dear, god, site, horribl, .]","[:, dear, god, site, horribl, .]",[:dear god thi site is horrible.],[:dear god this site is horrible.],[],[]
2,2,"""::: Somebody will invariably try to add Relig...","[``, :, :, :, Somebody, will, invariably, try,...","[""::: Somebody will invariably try to add Reli...",0,"[``, :, :, :, somebodi, invari, tri, add, reli...","[``, :, :, :, somebodi, invari, tri, add, reli...","[""::: somebodi will invari tri to add religion...","[""::: somebodi will invari tri to add religion...",[],[]
3,3,""" \n\n It says it right there that it IS a typ...","[``, It, says, it, right, there, that, it, IS,...","["" \n\n It says it right there that it IS a ty...",0,"[``, it, say, right, is, type, ., the, ``, '',...","[``, it, say, right, is, type, ., the, ``, '',...","["" it say it right there that it is a type., t...","["" it say it right there that it is a type., t...",[],[]
4,4,""" \n\n == Before adding a new product to the l...","[``, ==, Before, adding, a, new, product, to, ...","["" \n\n == Before adding a new product to the ...",0,"[``, ==, befor, ad, new, product, list, ,, mak...","[``, ==, befor, ad, new, product, list, ,, mak...","["" == befor ad a new product to the list, make...","["" == befor ad a new product to the list, make...",[],[]

In [ ]:
df.to_csv('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/stemmed_df.csv')

In [ ]:
df_unordered.head()

,Unnamed: 0.1,Unnamed: 0,text,tokenized_text_words,tokenized_text_sents,label,porter_stem_words,snow_stem_words,porter_stem_sents,snow_stem_sents,lemma_words,lemma_sents
0,0,0,Thank you for understanding. I think very high...,"['Thank', 'you', 'for', 'understanding', '.', ...","['Thank you for understanding.', 'I think very...",0,"['thank', 'understand', '.', 'i', 'think', 'hi...","['thank', 'understand', '.', 'i', 'think', 'hi...","['thank you for understanding.', 'i think veri...","['thank you for understanding.', 'i think veri...",[],[]
1,1,1,:Dear god this site is horrible.,"[':', 'Dear', 'god', 'this', 'site', 'is', 'ho...",[':Dear god this site is horrible.'],0,"[':', 'dear', 'god', 'site', 'horribl', '.']","[':', 'dear', 'god', 'site', 'horribl', '.']",[':dear god thi site is horrible.'],[':dear god this site is horrible.'],[],[]
2,2,2,"""::: Somebody will invariably try to add Relig...","['``', ':', ':', ':', 'Somebody', 'will', 'inv...","['""::: Somebody will invariably try to add Rel...",0,"['``', ':', ':', ':', 'somebodi', 'invari', 't...","['``', ':', ':', ':', 'somebodi', 'invari', 't...","['""::: somebodi will invari tri to add religio...","['""::: somebodi will invari tri to add religio...",[],[]
3,3,3,""" \n\n It says it right there that it IS a typ...","['``', 'It', 'says', 'it', 'right', 'there', '...","['"" \n\n It says it right there that it IS a t...",0,"['``', 'it', 'say', 'right', 'is', 'type', '.'...","['``', 'it', 'say', 'right', 'is', 'type', '.'...","['"" it say it right there that it is a type.',...","['"" it say it right there that it is a type.',...",[],[]
4,4,4,""" \n\n == Before adding a new product to the l...","['``', '==', 'Before', 'adding', 'a', 'new', '...","['"" \n\n == Before adding a new product to the...",0,"['``', '==', 'befor', 'ad', 'new', 'product', ...","['``', '==', 'befor', 'ad', 'new', 'product', ...","['"" == befor ad a new product to the list, mak...","['"" == befor ad a new product to the list, mak...",[],[]

In [ ]:
import pandas as pd
import ast

df_drct_frm_csv = pd.read_csv('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/stemmed_df.csv')

df_cols = ['text', 'tokenized_text_words', 'tokenized_text_sents', 'porter_stem_words', 'snow_stem_words', 'porter_stem_sents', 'snow_stem_sents', 'lemma_words', 'lemma_sents']

def safe_literal_eval(val):
    if pd.isna(val):  # Check if the value is NaN
        return []  # Return empty list for NaN values
    try:
        return ast.literal_eval(val)
    except (ValueError, SyntaxError):
        # If it can't be evaluated as a list, return empty list
        return []

df_str_cols = df_drct_frm_csv[df_cols]
df = df_str_cols
df['tokenized_text_words'] = df_str_cols['tokenized_text_words'].apply(safe_literal_eval)
df['tokenized_text_sents'] = df_str_cols['tokenized_text_sents'].apply(safe_literal_eval)
df['porter_stem_words'] = df_str_cols['porter_stem_words'].apply(safe_literal_eval)
df['snow_stem_words'] = df_str_cols['snow_stem_words'].apply(safe_literal_eval)
df['porter_stem_sents'] = df_str_cols['porter_stem_sents'].apply(safe_literal_eval)

<ipython-input-2-7948f0106632>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokenized_text_words'] = df_str_cols['tokenized_text_words'].apply(safe_literal_eval)
<ipython-input-2-7948f0106632>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokenized_text_sents'] = df_str_cols['tokenized_text_sents'].apply(safe_literal_eval)
<ipython-input-2-7948f0106632>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['porter_stem_words'] = df_str_cols['porter_stem_words'].apply(safe_literal_eval)
<ipython-input-2-7948f0106632>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['snow_stem_words'] = df_str_cols['snow_stem_words'].apply(safe_literal_eval)
<ipython-input-2-7948f0106632>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['porter_stem_sents'] = df_str_cols['porter_stem_sents'].apply(safe_literal_eval)

uses tokenized sents instead of tokenized words

In [ ]:
for index, row in df.iterrows():
    stemmed_sents = []

    for sent in row['tokenized_text_sents']:
        # Split sentence into words
        words = sent.split()

        # Stem each word individually
        stemmed_words_in_sent = []
        for word in words:
            try:
                stemmed_word = stemmer_ss.stem(word)
                stemmed_words_in_sent.append(stemmed_word)
            except RecursionError:
                print(f'RecursionError in row {index} on word: {word}')
                # Use original word if stemming fails
                stemmed_words_in_sent.append(word)

        # Rejoin the stemmed words into a sentence
        stemmed_sent = ' '.join(stemmed_words_in_sent)
        stemmed_sents.append(stemmed_sent)

    # Assign the stemmed sentences to the current row

In [ ]:
print(df['tokenized_text_words'][0], df['porter_stem_sents'][0], df['snow_stem_sents'][0])

['Thank', 'you', 'for', 'understanding', '.', 'I', 'think', 'very', 'highly', 'of', 'you', 'and', 'would', 'not', 'revert', 'without', 'discussion', '.'] ['thank you for understanding.', 'i think veri highli of you and would not revert without discussion.'] ['thank you for understanding.', 'i think veri high of you and would not revert without discussion.']

In [ ]:
print(df['tokenized_text_words'][0], df['porter_stem_sents'][0], df['snow_stem_sents'][0])

['Thank', 'you', 'for', 'understanding', '.', 'I', 'think', 'very', 'highly', 'of', 'you', 'and', 'would', 'not', 'revert', 'without', 'discussion', '.'] thank understand. i think highli would revert without discuss. thank understand. i think high would revert without discuss.

In [ ]:
df['text'][0]

'Thank you for understanding. I think very highly of you and would not revert without discussion.'

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

## this works

In [ ]:
stemmer_ps = PorterStemmer()
stemmer_ss = SnowballStemmer('english')

stemmed_words = []
stemmed_words_in_sent = []
stemmed_sentences = []

for word in df['tokenized_text_words'][0]:
    if word == '.':
        # Join the stemmed words with spaces to form a sentence
        if stemmed_words_in_sent:
            stemmed_sent = ' '.join(stemmed_words_in_sent) + '.'
            stemmed_sentences.append(stemmed_sent)
            # Reset for the next sentence
            stemmed_words_in_sent = []
    elif word not in stop_words:
        stemmed_word = stemmer_ss.stem(word)
        stemmed_words_in_sent.append(stemmed_word)

# Check if there are any words left after the loop
# (This handles text that doesn't end with a period)
if stemmed_words_in_sent:
    stemmed_sent = ' '.join(stemmed_words_in_sent)
    stemmed_sentences.append(stemmed_sent)

# Join all sentences with spaces if needed
full_text = ' '.join(stemmed_sentences)

print(full_text)

thank understand. i think high would revert without discuss.

In [ ]:
stemmer_ps = PorterStemmer()
stemmer_ss = SnowballStemmer('english')
stop_words = set(stopwords.words('english'))
stemmed_words = []
stemmed_words_in_sent = []
stemmed_sentences = []

for index, row in df.iterrows():
    for word in row['tokenized_text_words']:
      if word == '.':
          # Join the stemmed words with spaces to form a sentence
          if stemmed_words_in_sent:
              stemmed_sent = ' '.join(stemmed_words_in_sent) + '.'
              stemmed_sentences.append(stemmed_sent)
              # Reset for the next sentence
              stemmed_words_in_sent = []
      elif word not in stop_words:
          try:
            stemmed_word = stemmer_ss.stem(word)

          except RecursionError:
            print(f'recurssion error: {word}')

          stemmed_words_in_sent.append(stemmed_word)

  # Check if there are any words left after the loop
  # (This handles text that doesn't end with a period)
      if stemmed_words_in_sent:
        stemmed_sent = ' '.join(stemmed_words_in_sent)
        stemmed_sentences.append(stemmed_sent)

    # Join all sentences with spaces if needed
    full_text = ' '.join(stemmed_sentences)
    row['snow_stem_sents'] = full_text

NameError: name 'PorterStemmer' is not defined

In [ ]:
stemmer_ps = PorterStemmer()
stemmer_ss = SnowballStemmer('english')
stop_words = set(stopwords.words('english'))
stemmed_words = []
stemmed_words_in_sent = []
stemmed_sentences = []


for index, row in df.iterrows():
    stemmed_words_in_sent = []
    stemmed_sentences = []

    for word in row['tokenized_text_words']:
        if word in ['.', '!', '?']:
        #if word == '.':
            if stemmed_words_in_sent:
                stemmed_sent = ' '.join(stemmed_words_in_sent) + f'{word}'
                # stemmed_sent = ' '.join(stemmed_words_in_sent) + '.'
                stemmed_sentences.append(stemmed_sent)
                stemmed_words_in_sent = []  # Clear list
        elif word not in stop_words:
            try:
                stemmed_word = stemmer_ss.stem(word)
                stemmed_words_in_sent.append(stemmed_word)
            except RecursionError:
                print(f'recursion error: {word}')

    # Handle any remaining words in the last sentence
    if stemmed_words_in_sent:
        stemmed_sent = ' '.join(stemmed_words_in_sent)
        stemmed_sentences.append(stemmed_sent)

    # Assign directly without intermediate variable
    df.at[index, 'snow_stem_sents'] = ' '.join(stemmed_sentences)

    # Optional: force garbage collection periodically
    if index % 1000 == 0:
        import gc
        gc.collect()

In [ ]:
print(df['snow_stem_sents'][0])

thank understand. i think high would revert without discuss.

In [ ]:
stemmer_ps = PorterStemmer()
stop_words = set(stopwords.words('english'))
stemmed_words = []
stemmed_words_in_sent = []
stemmed_sentences = []


for index, row in df.iterrows():
    stemmed_words_in_sent = []
    stemmed_sentences = []

    for word in row['tokenized_text_words']:
      # logic for punctuation
        if word in ['.', '!', '?']:
       # if word == '.':
            if stemmed_words_in_sent:
              # plus needed punctuation character
                stemmed_sent = ' '.join(stemmed_words_in_sent) + f'{word}'
                stemmed_sentences.append(stemmed_sent)
                stemmed_words_in_sent = []  # Clear list
        elif word not in stop_words:
            try:
                stemmed_word = stemmer_ps.stem(word)
                stemmed_words_in_sent.append(stemmed_word)
            except RecursionError:
                print(f'recursion error: {word}')

    # Handle any remaining words in the last sentence
    if stemmed_words_in_sent:
        stemmed_sent = ' '.join(stemmed_words_in_sent)
        stemmed_sentences.append(stemmed_sent)

    # Assign directly without intermediate variable
    df.at[index, 'porter_stem_sents'] = ' '.join(stemmed_sentences)

    # Optional: force garbage collection periodically
    if index % 1000 == 0:
        import gc
        gc.collect()

KeyboardInterrupt:

In [ ]:
df.to_csv('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/stem_sent_df.csv')

In [ ]:
import pandas as pd
import ast
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

df_drct_frm_csv = pd.read_csv('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/tokenized_df.csv')


df_stem_frm_csv = pd.read_csv('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/stem_sent_df.csv')

df_stem_frm_csv['label'] = df_drct_frm_csv['label']

df_cols = ['text', 'tokenized_text_words', 'tokenized_text_sents', 'porter_stem_words', 'snow_stem_words', 'porter_stem_sents', 'snow_stem_sents', 'lemma_words', 'lemma_sents', 'label']

def safe_literal_eval(val):
    if pd.isna(val):  # Check if the value is NaN
        return []  # Return empty list for NaN values
    try:
        return ast.literal_eval(val)
    except (ValueError, SyntaxError):
        # If it can't be evaluated as a list, return empty list
        return []

df_str_cols = df_stem_frm_csv[df_cols]
df = df_str_cols
df['tokenized_text_words'] = df_str_cols['tokenized_text_words'].apply(safe_literal_eval)
df['tokenized_text_sents'] = df_str_cols['tokenized_text_sents'].apply(safe_literal_eval)
df['porter_stem_words'] = df_str_cols['porter_stem_words'].apply(safe_literal_eval)
df['snow_stem_words'] = df_str_cols['snow_stem_words'].apply(safe_literal_eval)
df['porter_stem_sents'] = df_str_cols['porter_stem_sents'].apply(safe_literal_eval)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
<ipython-input-5-0ac6c36f5448>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokenized_text_words'] = df_str_cols['tokenized_text_words'].apply(safe_literal_eval)
<ipython-input-5-0ac6c36f5448>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tokenized_text_sents'] = df_str_cols['tokenized_text_sents'].apply(safe_literal_eval)
<ipython-input-5-0ac6c36f5448>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['porter_stem_words'] = df_str_cols['porter_stem_words'].apply(safe_literal_eval)
<ipython-input-5-0ac6c36f5448>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['snow_stem_words'] = df_str_cols['snow_stem_words'].apply(safe_literal_eval)
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<ipython-input-5-0ac6c36f5448>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['porter_stem_sents'] = df_str_cols['porter_stem_sents'].apply(safe_literal_eval)

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
# lemmatized words

for index, row in df.iterrows():
  lemmatized_word = []
  lemmatized_words = []
  for word in row['tokenized_text_words']:
    if word not in stop_words:
      lemmatized_word = lemmatizer.lemmatize(word)
      lemmatized_words.append(lemmatized_word)

  df.at[index, 'lemma_words'] = lemmatized_words

In [ ]:
df.head(10)

,text,tokenized_text_words,tokenized_text_sents,porter_stem_words,snow_stem_words,porter_stem_sents,snow_stem_sents,lemma_words,lemma_sents
0,Thank you for understanding. I think very high...,"[Thank, you, for, understanding, ., I, think, ...","[Thank you for understanding., I think very hi...","[thank, understand, ., i, think, highli, would...","[thank, understand, ., i, think, high, would, ...",thank understand. i think highli would revert ...,thank understand. i think high would revert wi...,"[Thank, understanding, ., I, think, highly, wo...",[]
1,:Dear god this site is horrible.,"[:, Dear, god, this, site, is, horrible, .]",[:Dear god this site is horrible.],"[:, dear, god, site, horribl, .]","[:, dear, god, site, horribl, .]",: dear god site horribl.,: dear god site horribl.,"[:, Dear, god, site, horrible, .]",[]
2,"""::: Somebody will invariably try to add Relig...","[``, :, :, :, Somebody, will, invariably, try,...","[""::: Somebody will invariably try to add Reli...","[``, :, :, :, somebodi, invari, tri, add, reli...","[``, :, :, :, somebodi, invari, tri, add, reli...",`` : : : somebodi invari tri add religion? rea...,`` : : : somebodi invari tri add religion? rea...,"[``, :, :, :, Somebody, invariably, try, add, ...",[]
3,""" \n\n It says it right there that it IS a typ...","[``, It, says, it, right, there, that, it, IS,...","["" \n\n It says it right there that it IS a ty...","[``, it, say, right, is, type, ., the, ``, '',...","[``, it, say, right, is, type, ., the, ``, '',...",`` it say right is type. the `` '' type '' '' ...,`` it say right is type. the `` '' type '' '' ...,"[``, It, say, right, IS, type, ., The, ``, '',...",[]
4,""" \n\n == Before adding a new product to the l...","[``, ==, Before, adding, a, new, product, to, ...","["" \n\n == Before adding a new product to the ...","[``, ==, befor, ad, new, product, list, ,, mak...","[``, ==, befor, ad, new, product, list, ,, mak...","`` == befor ad new product list , make sure 's...","`` == befor ad new product list , make sure 's...","[``, ==, Before, adding, new, product, list, ,...",[]
5,this other one from 1897,"[this, other, one, from, 1897]",[this other one from 1897],"[one, 1897]","[one, 1897]",one 1897,one 1897,"[one, 1897]",[]
6,== Reason for banning throwing == \n\n This ar...,"[==, Reason, for, banning, throwing, ==, This,...",[== Reason for banning throwing == \n\n This a...,"[==, reason, ban, throw, ==, thi, articl, need...","[==, reason, ban, throw, ==, this, articl, nee...",== reason ban throw == thi articl need section...,== reason ban throw == this articl need sectio...,"[==, Reason, banning, throwing, ==, This, arti...",[]
7,|blocked]] from editing Wikipedia. |,"[|blocked, ], ], from, editing, Wikipedia, ., |]","[|blocked]] from editing Wikipedia., |]","[|block, ], ], edit, wikipedia, ., |]","[|block, ], ], edit, wikipedia, ., |]",|block ] ] edit wikipedia. |,|block ] ] edit wikipedia. |,"[|blocked, ], ], editing, Wikipedia, ., |]",[]
8,"== Arabs are committing genocide in Iraq, but ...","[==, Arabs, are, committing, genocide, in, Ira...","[== Arabs are committing genocide in Iraq, but...","[==, arab, commit, genocid, iraq, ,, protest, ...","[==, arab, commit, genocid, iraq, ,, protest, ...","== arab commit genocid iraq , protest europ. =...","== arab commit genocid iraq , protest europ. =...","[==, Arabs, committing, genocide, Iraq, ,, pro...",[]
9,Please stop. If you continue to vandalize Wiki...,"[Please, stop, ., If, you, continue, to, vanda...","[Please stop., If you continue to vandalize Wi...","[pleas, stop, ., if, continu, vandal, wikipedi...","[pleas, stop, ., if, continu, vandal, wikipedi...","pleas stop. if continu vandal wikipedia , homo...","pleas stop. if continu vandal wikipedia , homo...","[Please, stop, ., If, continue, vandalize, Wik...",[]

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatized_words = []
lemmatized_words_in_sent = []
lemmatized_sentences = []


# Helper function to convert NLTK POS tags to WordNet POS tags
def get_wordnet_pos(nltk_tag):
    if nltk_tag.startswith('J'):
        return wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return wordnet.VERB
    elif nltk_tag.startswith('N'):
        return wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return wordnet.ADV
    else:
        # Default is noun
        return wordnet.NOUN

for index, row in df.iterrows():
    lemmatized_words_in_sent = []
    lemmatized_sentences = []

    for word in row['tokenized_text_words']:
      # logic for punctuation
        if word in ['.', '!', '?']:
       # if word == '.':
            if lemmatized_words_in_sent:
              # plus needed punctuation character
                lemmatized_sent = ' '.join(lemmatized_words_in_sent) + f'{word}'
                lemmatized_sentences.append(lemmatized_sent)
                lemmatized_words_in_sent = []  # Clear list
        elif word not in stop_words:
            try:
                lemmatized_word = lemmatizer.lemmatize(word)
                lemmatized_words_in_sent.append(lemmatized_word)
            except RecursionError:
                print(f'recursion error: {word}')

    # Handle any remaining words in the last sentence
    if lemmatized_words_in_sent:
        lemmatized_sent = ' '.join(lemmatized_words_in_sent)
        lemmatized_sentences.append(lemmatized_sent)

    # Assign directly without intermediate variable
    df.at[index, 'lemma_sents'] = ' '.join(lemmatized_sentences)

    # Optional: force garbage collection periodically
    if index % 1000 == 0:
        import gc
        gc.collect()

In [ ]:
df.head(4)

,text,tokenized_text_words,tokenized_text_sents,porter_stem_words,snow_stem_words,porter_stem_sents,snow_stem_sents,lemma_words,lemma_sents,label
0,Thank you for understanding. I think very high...,"[Thank, you, for, understanding, ., I, think, ...","[Thank you for understanding., I think very hi...","[thank, understand, ., i, think, highli, would...","[thank, understand, ., i, think, high, would, ...",[],thank understand. i think high would revert wi...,"[Thank, understanding, ., I, think, highly, wo...",Thank understanding. I think highly would reve...,0
1,:Dear god this site is horrible.,"[:, Dear, god, this, site, is, horrible, .]",[:Dear god this site is horrible.],"[:, dear, god, site, horribl, .]","[:, dear, god, site, horribl, .]",[],: dear god site horribl.,"[:, Dear, god, site, horrible, .]",: Dear god site horrible.,0
2,"""::: Somebody will invariably try to add Relig...","[``, :, :, :, Somebody, will, invariably, try,...","[""::: Somebody will invariably try to add Reli...","[``, :, :, :, somebodi, invari, tri, add, reli...","[``, :, :, :, somebodi, invari, tri, add, reli...",[],`` : : : somebodi invari tri add religion ? re...,"[``, :, :, :, Somebody, invariably, try, add, ...",`` : : : Somebody invariably try add Religion?...,0
3,""" \n\n It says it right there that it IS a typ...","[``, It, says, it, right, there, that, it, IS,...","["" \n\n It says it right there that it IS a ty...","[``, it, say, right, is, type, ., the, ``, '',...","[``, it, say, right, is, type, ., the, ``, '',...",[],`` it say right is type. the `` '' type '' '' ...,"[``, It, say, right, IS, type, ., The, ``, '',...",`` It say right IS type. The `` '' Type '' '' ...,0

In [ ]:
df_cb = pd.read_csv('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/tokenized_df.csv')

df4join = df.copy()

#df4join.join(df_cb, how='left', lsuffix='_cpy')

pd.concat([df4join, df_cb], axis=1)

df4join.head(3)

,text,tokenized_text_words,tokenized_text_sents,porter_stem_words,snow_stem_words,porter_stem_sents,snow_stem_sents,lemma_words,lemma_sents
0,Thank you for understanding. I think very high...,"[Thank, you, for, understanding, ., I, think, ...","[Thank you for understanding., I think very hi...","[thank, understand, ., i, think, highli, would...","[thank, understand, ., i, think, high, would, ...",[],thank understand. i think high would revert wi...,"[Thank, understanding, ., I, think, highly, wo...",Thank understanding. I think highly would reve...
1,:Dear god this site is horrible.,"[:, Dear, god, this, site, is, horrible, .]",[:Dear god this site is horrible.],"[:, dear, god, site, horribl, .]","[:, dear, god, site, horribl, .]",[],: dear god site horribl.,"[:, Dear, god, site, horrible, .]",: Dear god site horrible.
2,"""::: Somebody will invariably try to add Relig...","[``, :, :, :, Somebody, will, invariably, try,...","[""::: Somebody will invariably try to add Reli...","[``, :, :, :, somebodi, invari, tri, add, reli...","[``, :, :, :, somebodi, invari, tri, add, reli...",[],`` : : : somebodi invari tri add religion ? re...,"[``, :, :, :, Somebody, invariably, try, add, ...",`` : : : Somebody invariably try add Religion?...

In [ ]:
df4join = df.copy()

df4join['label'] = df_cb['label']

In [ ]:
df4join.head(3)

,text,tokenized_text_words,tokenized_text_sents,porter_stem_words,snow_stem_words,porter_stem_sents,snow_stem_sents,lemma_words,lemma_sents,label
0,Thank you for understanding. I think very high...,"[Thank, you, for, understanding, ., I, think, ...","[Thank you for understanding., I think very hi...","[thank, understand, ., i, think, highli, would...","[thank, understand, ., i, think, high, would, ...",[],thank understand. i think high would revert wi...,"[Thank, understanding, ., I, think, highly, wo...",Thank understanding. I think highly would reve...,0
1,:Dear god this site is horrible.,"[:, Dear, god, this, site, is, horrible, .]",[:Dear god this site is horrible.],"[:, dear, god, site, horribl, .]","[:, dear, god, site, horribl, .]",[],: dear god site horribl.,"[:, Dear, god, site, horrible, .]",: Dear god site horrible.,0
2,"""::: Somebody will invariably try to add Relig...","[``, :, :, :, Somebody, will, invariably, try,...","[""::: Somebody will invariably try to add Reli...","[``, :, :, :, somebodi, invari, tri, add, reli...","[``, :, :, :, somebodi, invari, tri, add, reli...",[],`` : : : somebodi invari tri add religion ? re...,"[``, :, :, :, Somebody, invariably, try, add, ...",`` : : : Somebody invariably try add Religion?...,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302875 entries, 0 to 302874
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   text                  302875 non-null  object
 1   tokenized_text_words  302875 non-null  object
 2   tokenized_text_sents  302875 non-null  object
 3   porter_stem_words     302875 non-null  object
 4   snow_stem_words       302875 non-null  object
 5   porter_stem_sents     302875 non-null  object
 6   snow_stem_sents       302870 non-null  object
 7   lemma_words           302875 non-null  object
 8   lemma_sents           302875 non-null  object
 9   label                 302875 non-null  int64
dtypes: int64(1), object(9)
memory usage: 23.1+ MB

In [ ]:
df.to_csv('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/lemmatized_df.csv')

almost ran into a system RAM error ∨ ∨

In [ ]:
import pandas as pd
import ast
import nltk

df_str_cols = pd.read_csv('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/lemmatized_df.csv')


def safe_literal_eval(val):
    if pd.isna(val):  # Check if the value is NaN
        return []  # Return empty list for NaN values
    try:
        return ast.literal_eval(val)
    except (ValueError, SyntaxError):
        # If it can't be evaluated as a list, return empty list
        return []

df = df_str_cols
df['tokenized_text_words'] = df_str_cols['tokenized_text_words'].apply(safe_literal_eval)
df['tokenized_text_sents'] = df_str_cols['tokenized_text_sents'].apply(safe_literal_eval)
df['porter_stem_words'] = df_str_cols['porter_stem_words'].apply(safe_literal_eval)
df['snow_stem_words'] = df_str_cols['snow_stem_words'].apply(safe_literal_eval)
df['porter_stem_sents'] = df_str_cols['porter_stem_sents'].apply(safe_literal_eval)
df['snow_stem_sents'] = df_str_cols['snow_stem_sents'].apply(safe_literal_eval)
df['lemma_words'] = df_str_cols['lemma_words'].apply(safe_literal_eval)
df['lemma_sents'] = df_str_cols['lemma_sents'].apply(safe_literal_eval)

<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal
<unknown>:1: SyntaxWarning: invalid decimal literal

In [ ]:
df_str_cols.head(3)

,Unnamed: 0,text,tokenized_text_words,tokenized_text_sents,porter_stem_words,snow_stem_words,porter_stem_sents,snow_stem_sents,lemma_words,lemma_sents
0,0,Thank you for understanding. I think very high...,"[Thank, you, for, understanding, ., I, think, ...","[Thank you for understanding., I think very hi...","[thank, understand, ., i, think, highli, would...","[thank, understand, ., i, think, high, would, ...",[],thank understand. i think high would revert wi...,"[Thank, understanding, ., I, think, highly, wo...",[]
1,1,:Dear god this site is horrible.,"[:, Dear, god, this, site, is, horrible, .]",[:Dear god this site is horrible.],"[:, dear, god, site, horribl, .]","[:, dear, god, site, horribl, .]",[],: dear god site horribl.,"[:, Dear, god, site, horrible, .]",[]
2,2,"""::: Somebody will invariably try to add Relig...","[``, :, :, :, Somebody, will, invariably, try,...","[""::: Somebody will invariably try to add Reli...","[``, :, :, :, somebodi, invari, tri, add, reli...","[``, :, :, :, somebodi, invari, tri, add, reli...",[],`` : : : somebodi invari tri add religion ? re...,"[``, :, :, :, Somebody, invariably, try, add, ...",[]

In [ ]:
df.head(3)

,Unnamed: 0,text,tokenized_text_words,tokenized_text_sents,porter_stem_words,snow_stem_words,porter_stem_sents,snow_stem_sents,lemma_words,lemma_sents,label
0,0,Thank you for understanding. I think very high...,"[Thank, you, for, understanding, ., I, think, ...","[Thank you for understanding., I think very hi...","[thank, understand, ., i, think, highli, would...","[thank, understand, ., i, think, high, would, ...",[],[],"[Thank, understanding, ., I, think, highly, wo...",[],0
1,1,:Dear god this site is horrible.,"[:, Dear, god, this, site, is, horrible, .]",[:Dear god this site is horrible.],"[:, dear, god, site, horribl, .]","[:, dear, god, site, horribl, .]",[],[],"[:, Dear, god, site, horrible, .]",[],0
2,2,"""::: Somebody will invariably try to add Relig...","[``, :, :, :, Somebody, will, invariably, try,...","[""::: Somebody will invariably try to add Reli...","[``, :, :, :, somebodi, invari, tri, add, reli...","[``, :, :, :, somebodi, invari, tri, add, reli...",[],[],"[``, :, :, :, Somebody, invariably, try, add, ...",[],0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302875 entries, 0 to 302874
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Unnamed: 0            302875 non-null  int64
 1   text                  302875 non-null  object
 2   tokenized_text_words  302875 non-null  object
 3   tokenized_text_sents  302875 non-null  object
 4   porter_stem_words     302875 non-null  object
 5   snow_stem_words       302875 non-null  object
 6   porter_stem_sents     302875 non-null  object
 7   snow_stem_sents       302870 non-null  object
 8   lemma_words           302875 non-null  object
 9   lemma_sents           302875 non-null  object
dtypes: int64(1), object(9)
memory usage: 23.1+ MB

In [ ]:
df_cb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302875 entries, 0 to 302874
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Unnamed: 0            302875 non-null  int64
 1   text                  302875 non-null  object
 2   tokenized_text_words  302873 non-null  object
 3   tokenized_text_sents  302873 non-null  object
 4   label                 302875 non-null  int64
dtypes: int64(2), object(3)
memory usage: 11.6+ MB

In [ ]:
df.join(df_cb, how='outer')

In [ ]:
enc_text = df['text'].tolist()
enc_label = df['label']

'3 3. 3 3 3 3 3 3 3.'

## no porter sentences

In [ ]:
df.head(10)

,text,tokenized_text_words,tokenized_text_sents,porter_stem_words,snow_stem_words,porter_stem_sents,snow_stem_sents,lemma_words,lemma_sents
0,Thank you for understanding. I think very high...,"[Thank, you, for, understanding, ., I, think, ...","[Thank you for understanding., I think very hi...","[thank, understand, ., i, think, highli, would...","[thank, understand, ., i, think, high, would, ...",thank understand. i think highli would revert ...,thank understand. i think high would revert wi...,[],[]
1,:Dear god this site is horrible.,"[:, Dear, god, this, site, is, horrible, .]",[:Dear god this site is horrible.],"[:, dear, god, site, horribl, .]","[:, dear, god, site, horribl, .]",: dear god site horribl.,: dear god site horribl.,[],[]
2,"""::: Somebody will invariably try to add Relig...","[``, :, :, :, Somebody, will, invariably, try,...","[""::: Somebody will invariably try to add Reli...","[``, :, :, :, somebodi, invari, tri, add, reli...","[``, :, :, :, somebodi, invari, tri, add, reli...",`` : : : somebodi invari tri add religion? rea...,`` : : : somebodi invari tri add religion? rea...,[],[]
3,""" \n\n It says it right there that it IS a typ...","[``, It, says, it, right, there, that, it, IS,...","["" \n\n It says it right there that it IS a ty...","[``, it, say, right, is, type, ., the, ``, '',...","[``, it, say, right, is, type, ., the, ``, '',...",`` it say right is type. the `` '' type '' '' ...,`` it say right is type. the `` '' type '' '' ...,[],[]
4,""" \n\n == Before adding a new product to the l...","[``, ==, Before, adding, a, new, product, to, ...","["" \n\n == Before adding a new product to the ...","[``, ==, befor, ad, new, product, list, ,, mak...","[``, ==, befor, ad, new, product, list, ,, mak...","`` == befor ad new product list , make sure 's...","`` == befor ad new product list , make sure 's...",[],[]
5,this other one from 1897,"[this, other, one, from, 1897]",[this other one from 1897],"[one, 1897]","[one, 1897]",one 1897,one 1897,[],[]
6,== Reason for banning throwing == \n\n This ar...,"[==, Reason, for, banning, throwing, ==, This,...",[== Reason for banning throwing == \n\n This a...,"[==, reason, ban, throw, ==, thi, articl, need...","[==, reason, ban, throw, ==, this, articl, nee...",== reason ban throw == thi articl need section...,== reason ban throw == this articl need sectio...,[],[]
7,|blocked]] from editing Wikipedia. |,"[|blocked, ], ], from, editing, Wikipedia, ., |]","[|blocked]] from editing Wikipedia., |]","[|block, ], ], edit, wikipedia, ., |]","[|block, ], ], edit, wikipedia, ., |]",|block ] ] edit wikipedia. |,|block ] ] edit wikipedia. |,[],[]
8,"== Arabs are committing genocide in Iraq, but ...","[==, Arabs, are, committing, genocide, in, Ira...","[== Arabs are committing genocide in Iraq, but...","[==, arab, commit, genocid, iraq, ,, protest, ...","[==, arab, commit, genocid, iraq, ,, protest, ...","== arab commit genocid iraq , protest europ. =...","== arab commit genocid iraq , protest europ. =...",[],[]
9,Please stop. If you continue to vandalize Wiki...,"[Please, stop, ., If, you, continue, to, vanda...","[Please stop., If you continue to vandalize Wi...","[pleas, stop, ., if, continu, vandal, wikipedi...","[pleas, stop, ., if, continu, vandal, wikipedi...","pleas stop. if continu vandal wikipedia , homo...","pleas stop. if continu vandal wikipedia , homo...",[],[]

# saving as words

In [ ]:
words = []
sents = []

for index, row in df.iterrows():
    for word in row['tokenized_text_words']:
        words.append(word)
    for sent in row['tokenized_text_sents']:
        sents.append(sent)

In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
final_tokens = []

for each in words:
    if each not in stop_words:
        final_tokens.append(each)

In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer

stemmer_ps = PorterStemmer()
stemmed_words_ps = []
problem_words_ps = []
stemmed_words_ss = []
problem_words_ss = []

# Process words individually with error handling
for word in words:
    try:
        stemmed_words_ps.append(stemmer_ps.stem(word))
    except RecursionError:
        # Fallback to another stemmer or keep the original word
        problem_words_ps.append(word)
        stemmed_words_ps.append(word)  # or use another stemmer as fallback

stemmer_ss = SnowballStemmer('english')
for word in words:
    if word not in problem_words_ps:
        try:
            stemmed_words_ss.append(stemmer_ss.stem(word))
        except RecursionError:
            problem_words_ss.append(word)
            stemmed_words_ss.append(word)

In [ ]:
problem_words_ps

['yyyyyyyyyyyyyyybvgtfrrrrrbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy']

In [ ]:
with open('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/stemmed_words_ps.txt', 'w') as file:
  file.write('\n'.join(stemmed_words_ps))
with open('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/stemmed_words_ss.txt', 'w') as file:
  file.write('\n'.join(stemmed_words_ss))
with open('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/word_list.txt', 'w') as file:
  file.write('\n'.join(words))

In [ ]:
with open('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/stemmed_words_ps.txt', 'r') as f:
    stemmed_words_ps = f.readlines()
stemmed_words_ps = [word.strip() for word in stemmed_words_ps]

with open('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/stemmed_words_ss.txt', 'r') as f:
    stemmed_words_ss = f.readlines()
stemmed_words_ss = [word.strip() for word in stemmed_words_ss]

with open('/content/drive/MyDrive/ML/Machine Learning/NLP/Data/word_list.txt', 'r') as f:
    words = f.readlines()
words = [word.strip() for word in words]